language: c
cache: ccache
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILDDIR=. TOOL="./configure --warn"
    - os: linux
      compiler: gcc
      env: BUILDDIR=. TOOL="./configure --warn --zlib-compat --native"
    - os: linux
      compiler: gcc
      env: BUILDDIR=../build TOOL="../zlib-ng/configure --warn --zlib-compat"
    - os: linux
      compiler: gcc
      env: BUILDDIR=. TOOL="./configure --warn --zlib-compat --without-optimizations --without-new-strategies"
    - os: linux
      compiler: gcc
      env: BUILDDIR=. TOOL="cmake ."
    - os: linux
      compiler: gcc
      env: BUILDDIR=../build TOOL="cmake ../zlib-ng"

    - os: linux
      compiler: clang
      env: BUILDDIR=. TOOL="./configure --warn --zlib-compat"
    - os: linux
      compiler: clang
      env: BUILDDIR=../build TOOL="cmake ../zlib-ng"

    - os: osx
      compiler: gcc
      env: BUILDDIR=. TOOL="./configure --warn --zlib-compat"
    - os: osx
      compiler: gcc
      env: BUILDDIR=../build TOOL="../zlib-ng/configure --warn --zlib-compat"
    - os: osx
      compiler: gcc
      env: BUILDDIR=. TOOL="cmake ."

    - os: osx
      compiler: clang
      env: BUILDDIR=. TOOL="./configure --warn --zlib-compat"
    - os: osx
      compiler: clang
      env: BUILDDIR=../build TOOL="cmake ../zlib-ng"

    # Cross compiling for arm variants
    - os: linux
      compiler: aarch64-linux-gnu-gcc
      addons:
        apt:
          packages:
            - qemu
            - gcc-aarch64-linux-gnu
            - libc-dev-arm64-cross
      # for all aarch64 implementations NEON is mandatory, while crypto/crc are not.
      # so for aarch64 neon should be automatically enabled, and "acle" should be explicitly defined
      env: CHOST=aarch64-linux-gnu BUILDDIR=. TOOL="./configure --warn --zlib-compat"
    - os: linux
      compiler: aarch64-linux-gnu-gcc
      addons:
        apt:
          packages:
            - qemu
            - gcc-aarch64-linux-gnu
            - libc-dev-arm64-cross
      # aarch64 toolchain in trusty is 4.8.2, which doesn't support acle intrinsics
      # until travis provides xenial dist (which comes with gcc-aarch64-5.3.1) 'acle' option cannot
      # be enabled in subset. but the command
      # "CHOST=aarch64-linux-gnu ./configure --warn --zlib-compat --acle"
      # should work if manually test it in a dist with gcc-aarch64 5.1 or higher
      # env: CHOST=aarch64-linux-gnu BUILDDIR=. TOOL="./configure --warn --zlib-compat --acle"
      env: CHOST=aarch64-linux-gnu BUILDDIR=. TOOL="./configure --warn --zlib-compat"
    # hardware float subsets
    - os: linux
      compiler: arm-linux-gnueabihf-gcc
      addons:
        apt:
          packages:
            - qemu
            - gcc-arm-linux-gnueabihf
            - libc-dev-armhf-cross
      env: CHOST=arm-linux-gnueabihf BUILDDIR=. TOOL="./configure --warn"
    - os: linux
      compiler: arm-linux-gnueabihf-gcc
      addons:
        apt:
          packages:
            - qemu
            - gcc-arm-linux-gnueabihf
            - libc-dev-armhf-cross
      env: CHOST=arm-linux-gnueabihf BUILDDIR=. TOOL="./configure --warn --zlib-compat --neon"
    - os: linux
      compiler: arm-linux-gnueabihf-gcc
      addons:
        apt:
          packages:
            - qemu
            - gcc-arm-linux-gnueabihf
            - libc-dev-armhf-cross
      env: CHOST=arm-linux-gnueabihf BUILDDIR=. TOOL="./configure --warn --zlib-compat"
    # software float subset
    - os: linux
      compiler: arm-linux-gnueabi-gcc
      addons:
        apt:
          packages:
            - qemu
            - gcc-arm-linux-gnueabi
            - libc-dev-armel-cross
      env: CHOST=arm-linux-gnueabi BUILDDIR=. TOOL="./configure"
    - os: linux
      compiler: arm-linux-gnueabi-gcc
      addons:
        apt:
          packages:
            - qemu
            - gcc-arm-linux-gnueabi
            - libc-dev-armel-cross
      env: CHOST=arm-linux-gnueabi BUILDDIR=. TOOL="./configure --zlib-compat"

script: mkdir -p $BUILDDIR && cd $BUILDDIR && $TOOL && make -j2 && make test
