sudo: required
language: c
dist: trusty

matrix:
  include:
    - os: linux
      compiler: aarch64-linux-gnu-gcc
      addons:
        apt:
          packages:
            - qemu
            - gcc-aarch64-linux-gnu
            - libc-dev-arm64-cross
      env: CHOST=aarch64-linux-gnu BUILDDIR=. TOOL="./configure --warn --zlib-compat --neon"
    - os: linux
      compiler: arm-linux-gnueabihf-gcc
      addons:
        apt:
          packages:
            - qemu
            - gcc-arm-linux-gnueabihf
            - libc-dev-armhf-cross
      env: CHOST=arm-linux-gnueabihf BUILDDIR=. TOOL="./configure --warn --zlib-compat --neon"
    - os: linux
      compiler: arm-linux-gnueabi-gcc
      addons:
        apt:
          packages:
            - qemu
            - gcc-arm-linux-gnueabi
            - libc-dev-armel-cross
      env: CHOST=arm-linux-gnueabi BUILDDIR=. TOOL="./configure --zlib-compat"



script:
    - mkdir -p $BUILDDIR && cd $BUILDDIR && $TOOL && make -j2 && make test
