sudo: required
language: c
cache: ccache
dist: trusty

addons:
  apt:
    packages:
    - qemu
    - autoconf
    - libtool
    - gcc-arm-linux-gnueabihf
    - gcc-aarch64-linux-gnu

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILDDIR=. TOOL="./configure --warn"
    - os: linux
      compiler: gcc
      env: BUILDDIR=. TOOL="./configure --warn --zlib-compat --native"
    - os: linux
      compiler: gcc
      env: BUILDDIR=../build TOOL="../zlib-ng/configure --warn --zlib-compat"
    - os: linux
      compiler: gcc
      env: BUILDDIR=. TOOL="./configure --warn --zlib-compat --without-optimizations --without-new-strategies"
    - os: linux
      compiler: gcc
      env: BUILDDIR=. TOOL="cmake ."
    - os: linux
      compiler: gcc
      env: BUILDDIR=../build TOOL="cmake ../zlib-ng"
    - os: linux
      compiler: aarch64-linux-gnu-gcc
      env: BUILDDIR=. TOOL="CHOST=aarch64-linux-gnu ./configure --warn --zlib-compat --neon"
    - os: linux
      compiler: arm-linux-gnueabihf-gcc
      env: BUILDDIR=. TOOL="CHOST=arm-linux-gnueabihf ./configure --warn --zlib-compat --neon"

    - os: linux
      compiler: clang
      env: BUILDDIR=. TOOL="./configure --warn --zlib-compat"
    - os: linux
      compiler: clang
      env: BUILDDIR=../build TOOL="cmake ../zlib-ng"

    - os: osx
      compiler: gcc
      env: BUILDDIR=. TOOL="./configure --warn --zlib-compat"
    - os: osx
      compiler: gcc
      env: BUILDDIR=../build TOOL="../zlib-ng/configure --warn --zlib-compat"
    - os: osx
      compiler: gcc
      env: BUILDDIR=. TOOL="cmake ."

    - os: osx
      compiler: clang
      env: BUILDDIR=. TOOL="./configure --warn --zlib-compat"
    - os: osx
      compiler: clang
      env: BUILDDIR=../build TOOL="cmake ../zlib-ng"

script:
    - mkdir -p $BUILDDIR && cd $BUILDDIR && $TOOL && make -j2 && make test
